### ISSUE TITLE
[PE-D] Missing contacts

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-T16-1/tp#157] opened 2021-10-30 08:03 UTC
![Screenshot 2021-10-29 at 4.59.41 PM.png](https://raw.githubusercontent.com/ruthpohrp/ped/main/files/c5f5b98b-97b6-4369-9dff-7fd14e30fe5e.png)
Screenshot 2021-10-29 at 4.59.41 PM

When I closed the app and reopened it and used it, I found some of my contacts missing (as you can see I have more than 5 contacts but somehow my 2 other contacts don't show in the list). (Not sure why)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: ruthpohrp/ped#13

**Comment by sebbycake** [comment] 2021-11-01 10:19
Left a comment on ruthpoh's issue to seek clarity

**Comment by sebbycake** [comment] 2021-11-05 08:34
Could not reproduce on our side, closing for now.

**Closed by sebbycake** 2021-11-05 08:34 UTC
Labels: type.Bug
